services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:80
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_HOST:     '${DB_HOST}'
    depends_on:
      - pgsql
  pgsql:
    image: 'postgres:15'
    container_name: database
    ports:
      - '${DB_PORT}:5472'
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db:/var/lib/postgresql/data
  blockchain:
    build:
      context: ./blockchain
    container_name: blockchain
    ports:
      - 7000:7000

volumes:
  db:
    driver: local
